import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Container,
  FormControlLabel,
  Checkbox,
  Button,
  Typography,
  FormGroup,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
} from '@mui/material';

const ConsentFormPage13 = () => {
  const navigate = useNavigate();
  const [shareInfo, setShareInfo] = useState(false);
  const [openDialog, setOpenDialog] = useState(false);

  const handleShareInfoChange = (event) => {
    setShareInfo(event.target.checked);
  };

  const handleContinue = () => {
    navigate('/consent-form/consentform-page14'); // specify the next page route here
  };

  const handleNotInterested = () => {
    setOpenDialog(true);
  };

  const handleCloseDialog = (confirmExit) => {
    setOpenDialog(false);
    if (confirmExit) {
      navigate('/'); // specify the exit route here
    }
  };

  return (
    <Container maxWidth="sm">
      <Container component="main" maxWidth="sm" sx={{ marginTop: 8 }}>
        <Typography variant="h6" gutterBottom>
          Audits of this study could be done by the funding sources (CIHR), the Nova Scotia Health Research Ethics Board, or the IWK Health Centre’s Research Ethics Board. In the case of an audit, your file could be reviewed. Anyone performing an audit would also keep your identity confidential.
        </Typography>
        <Typography paragraph>
          Healthcare providers/ NS Health may help us to recruit participants for the study. We may share information with them about their patients who are using Health enSuite Caregivers application. The appropriate act governing health information protection as noted through legislation in each province will be adhered to in the conduct of this study.
        </Typography>
        <FormGroup>
          <Typography paragraph>
            I would like to share my information with healthcare provider. (If you check Yes, then your sleep related progress report(s) that would be generated by you using the appropriate app feature will be shared with your primary care provider, and not with the institution.)
          </Typography>
          <FormControlLabel
            control={<Checkbox checked={shareInfo} onChange={handleShareInfoChange} />}
            label="Yes"
          />
        </FormGroup>
        <Button
          variant="outlined"
          color="primary"
          onClick={handleContinue}
          disabled={!shareInfo}
        >
          Continue
        </Button>
        <Button
          variant="outlined"
          color="secondary"
          onClick={handleNotInterested}
        >
          No thanks, I am not interested
        </Button>
      </Container>

      <Dialog
        open={openDialog}
        onClose={() => handleCloseDialog(false)}
      >
        <DialogTitle>Exit Confirmation</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Thank you for your interest in Health enSuite Caregivers. We understand you are not interested in participating in our study.
            <br /><br />
            Are you sure you want to exit?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => handleCloseDialog(false)} color="primary">
            Cancel
          </Button>
          <Button onClick={() => handleCloseDialog(true)} color="secondary" autoFocus>
            Yes, Exit
          </Button>
        </DialogActions>
      </Dialog>
    </Container>
  );
};

export default ConsentFormPage13;
